### PR TITLE
Json Output of Shm_Struct

### PR DESCRIPTION
**Pull request by altmind**
CoreFreq is an awesome project with a lot of utility.

I would like to be able to somehow get machine-readable info about the target machine.

The best I found so far is 'cpufreq-cli -s', but its missing a lot of interesting info(and not really machine readable).

I tried to experiment with python cffi( https://github.com/cyring/CoreFreq/compare/master...altmind:python-cffi ) but hit the roadblocks:
* cffi dont support __attribute__(aligned(64)). sizeof of C and cffi dont agree if removing aligned(64) from python generated header file. stripping aligned(64) from everywhere helps, but idk how this affect correctness.
* cffi cannot unmarshal structures like these `CPU_STRUCT		Cpu[];` that assume that structs sizes are stored elsewhere.

For the lack of better options, I've added an option to corefreq-cli: -j that produces single large mostly unprocessed json from SHM_STRUCT. No external json dependencies were introduced and I think I've covered almost every property of a struct.

I would really liked to see the code back in the upstream.
@cyring what do you think about this idea?

### CODE REVIEW

**Comment by cyring** [comment]
@altmind : Your code works fine. Great idea.

b/c I would like to focus on the remaining features of _CoreFreq_ , are you ok to maintain it ?

I also need to reorganize the project directory such as I did with [XFreq](https://github.com/cyring/xfreq): directories like drv, svr, cli, also bin, obj, inc and finally extra where your code would be stored (and why not: csv, xml, http, etc).

Sharing branches using GIT is what to do next.

**Comment by altmind** [comment]
Sure, I can maintain this feature. The biggest challenge will be keeping up with udpates in Shm_Struct, so I will keep an eye on the changes.

Regarding the directories, its your call. This will make project structure look cleaner.

**Comment by altmind** [comment]
Any input required from me?
I would be really happy to see this in upstream so I can use stock version of corefreq in my scripts %)

**Comment by cyring** [comment]
Files have been integrated into project.

Please stick to 80 columns and make use of the real tab char: I'm oftenly coding with console

The Json output seems big: can it be optimized ?

**Comment by altmind** [comment]
regarding code style, sure, i can do it.
but better, maybe you can create a clang-format config so everybody can reformat automatically?
this is stupiditly simple: https://gist.github.com/altmind/31ceb2d316cf56f29f487293d341b604



my intention with this json feature was to allow external programmatic access so new tools can be implemented.

readability was not a design goal. if you want to format output nicely, you can you jq for example, you can even filter out irrelevant parts of struct.

`corefreq-cli -j | jq .`

yet if you want readable json output, maybe i can create another command line option that will export similar output as in `corefreq-cli -s` encoded as json?

**Comment by cyring** [comment]
No thank you.
Exporting the shm structure is indeed where to focus. And I'm still trying to normalize values between différents architectures and models...

**Pull request merged**
