### PR TITLE
Use `on_cpu` instead of `wake_cpu` for better compatibility

### PR DESCRIPTION
**Pull request by RomanHargrave**
This appears to add support for BMQ, as best I can observe (there is no concrete documentation for the scheduler system).

### CODE REVIEW

**Comment by cyring** [comment]
Thanks, but I was not aware that the change impacts the CoreFreq api ; because I want to keep the `wake_cpu` field, across the all source code: `on_cpu` is not the good choice in non-BMQ build context.

At best, in the corefreqk.c driver, `on_cpu` has to be stored into `wake_cpu` if BMQ is defined.

**Comment by cyring** [comment]
Something like:

In corefreqk.c
```C
#if defined(CONFIG_SCHED_BMQ)
		SysGate->taskList[cnt].wake_cpu = (short int) thread->cpu; /* Put the CPU# at this line */
#else
		SysGate->taskList[cnt].wake_cpu = (short int) thread->wake_cpu;
#endif
```

**Comment by RomanHargrave** [comment]
> At best, in the corefreqk.c driver, on_cpu has to be stored into wake_cpu if BMQ is defined.

I had realized that at the time that I did this in may but neglected to fix it. It's easy enough to revert, I'll update tonight.

**Comment by RomanHargrave** [comment]
@cyring It's a little later, but I finally got around to it. The `wake_cpu` field is back to being called `wake_cpu` and `thread->cpu` is only used for BMQ kernels.

**Comment by cyring** [comment]
Sorry; meanwhile I have committed new changes.

**Comment by RomanHargrave** [comment]
> Sorry; meanwhile I have committed new changes.

Understandable. It took me ages to get around to this, after all; however, it looks like the fix in this PR isn't present, unless you mean to say that there is a merge conflict?

**Comment by cyring** [comment]
Yes I prefer to cancel this PR.

**Comment by cyring** [comment]
If you are OK, I'll add those lines ?

**Comment by RomanHargrave** [comment]
Sure

**Comment by cyring** [comment]
Done. Feel free to close the PR.

**Pull request closed without merging**
