### PR TITLE
Add links for AUR packages

### PR DESCRIPTION
**Pull request by inglor**
Closes: #228

### CODE REVIEW

**Comment by cyring** [comment]
Hello,

Nice addition into the documentation, thank you.  

But don't you think the AUR version sticker should reflect the version in source code ?
For example, the `develop` branch is currently as below:
https://github.com/cyring/CoreFreq/blob/a65b6f4f7a6d32595a0a4e581df74f1f6073f3af/coretypes.h#L8
Users may found odd that `About` window or `-v` option does not match with the AUR.  

Regards

**Comment by inglor** [comment]
Hi @cyring,

Versioning for the main package `corefreq` is based on git [tags] The latest git tag is 1.84. If you want to include the revision on next tag include it as well and I'll adjust accordingly.

For the `-git` packages version is automatically calculated based on [VCS_package_guidelines]. Archlinux users who uses the AUR should already be familiar with this.

[tags]: https://github.com/cyring/CoreFreq/releases
[VCS_package_guidelines]: https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git

**Comment by cyring** [comment]
> Hi @cyring,
> 
> Versioning for the main package `corefreq` is based on git [tags](https://github.com/cyring/CoreFreq/releases) The latest git tag is 1.84. If you want to include the revision on next tag include it as well and I'll adjust accordingly.
> 
> For the `-git` packages version is automatically calculated based on [VCS_package_guidelines](https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git). Archlinux users who uses the AUR should already be familiar with this.

Hello @inglor 

We can stay the same with revision.

About VCS I understand what you are facing to but I can already imagine that Users will ask and create issues just because they are getting lost with versions.
Is there any other mean we could add to dynamically show the _real_ version from repo ?

**Comment by inglor** [comment]
Yes but not recommend - a real version number such as `1.85` means it's released. Hard-coding the version to `1.85` means the `-git` package appear as "lower" than the installed version when `pacman` compares them - that's why the VCS packaging is like that to assert a newer HEAD will appear as newer in `pacman` as well i.e. an upgrade.

As for users of AUR they will first be looking at comments of the package before coming upstream to raise an issue so I can `pin` a comment explaining such discrepancy for the VCS package.

**Comment by cyring** [comment]
> As for users of AUR they will first be looking at comments of the package before coming upstream to raise an issue so I can `pin` a comment explaining such discrepancy for the VCS package.

OK, I will let under your control to `pin` any additional information.

**Pull request merged**
